module.exports = {
  "status": 0,
  "msg": "ok",
  "values": [{
    "app": "nebula",
    "id": 1,
    "name": "SQL注入"
  }, {
    "app": "nebula",
    "id": 2,
    "name": "RFI"
  }, {
    "app": "nebula",
    "id": 3,
    "name": "目录遍历"
  }, {
    "app": "nebula",
    "id": 4,
    "name": "XSS"
  }, {
    "app": "nebula",
    "id": 5,
    "name": "账号异常"
  }, {
    "app": "nebula",
    "id": 6,
    "name": "恶意扫描"
  }, {
    "app": "nebula",
    "id": 7,
    "name": "爬虫"
  }, {
    "app": "nebula",
    "id": 8,
    "name": "羊毛党"
  }, {
    "app": "nebula",
    "id": 9,
    "name": "撞库"
  }, {
    "app": "nebula",
    "id": 10,
    "name": "ngx_lua_waf"
  }, {
    "app": "nebula",
    "id": 11,
    "name": "恶意注册"}, {
    "app": "nebula",
    "id": 12,
    "name": "其他"
  }, {
    "app": "nebula",
    "id": 13,
    "name": "盗号"
  }, {
    "app": "nebula",
    "id": 14,
    "name": "刷单"
  }]
};
